version: '3.8'
services:
  web:
    build: 
      context: .
    volumes:
      - .:/app
    command: /bin/sh -c 'npm install && npm run dev'
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`direktory.biz`)"
      - "traefik.http.routers.frontend.tls=true"

  
