/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        fontFamily: {
            sans: ["Work Sans", "sans-serif"],
        },
        extend: {
            fontFamily: {
                "work-sans": ["Work Sans", "sans-serif"],
                "zilla-slab": ["Zilla Slab", "serif"],
            },
            colors: {
                primary: {
                    40: "#DAE0E5",
                    50: "#3399FF",
                    60: "#2877C7",
                    70: "#2163A6",
                },
                "my-gray": {
                    40: "#F2F5F7",
                    50: "#E7EDF2",
                    60: " #E6E6E6",
                    70: "#66737F",
                    80: "#5C6873",
                },
                dark: {
                    50: "#050F19",
                    60: "#02080D",
                },
            },
            borderWidth: {
                1: "1px",
            },
            borderRadius: {
                10: "10px",
            },
            height: {
                "90-screen": "90vh",
                "80-screen": "80vh",
                "70-screen": "70vh",
                "60-screen": "60vh",
                "50-screen": "50vh",
                "40-screen": "40vh",
                "30-screen": "30vh",
                "20-screen": "20vh",
                "10-screen": "10vh",
                "1-px": "1px",
                "2-px": "2px",
            },
            maxHeight: {
                "90-screen": "90vh",
                "80-screen": "80vh",
                "70-screen": "70vh",
                "65-screen": "65vh",
                "60-screen": "60vh",
                "55-screen": "55vh",
                "50-screen": "50vh",
                "40-screen": "40vh",
                "30-screen": "30vh",
                "20-screen": "20vh",
                "10-screen": "10vh",
            },
            minHeight: {
                "90-screen": "90vh",
                "80-screen": "80vh",
                "70-screen": "70vh",
                "63-screen": "63vh",
                "65-screen": "65vh",
                "60-screen": "60vh",
                "50-screen": "50vh",
                "40-screen": "40vh",
                "30-screen": "30vh",
                "20-screen": "20vh",
                "10-screen": "10vh",
                500: "500px",
                600: "600px",
                700: "700px",
                800: "800px",
            },
            minWidth: {
                "90-screen": "90vw",
                "80-screen": "80vw",
                "70-screen": "70vw",
                "60-screen": "60vw",
                "50-screen": "50vw",
                "40-screen": "40vw",
                "30-screen": "30vw",
                "25-screen": "25vw",
                "20-screen": "20vw",
                "10-screen": "10vw",
                500: "500px",
                600: "600px",
                700: "700px",
                800: "800px",
            },
        },
    },
    plugins: [],
};
